### ISSUE TITLE
manual class colors

### ISSUE THREAD

**Issue by kroovysteph** [Vladinator/wow-addon-friendlistcolors#1]
hi, vladinator

i want to achieve something like:

[color=**paladin**] Uther [/color]

i tried something like this: https://pastebin.com/RqKRBm7K
...but it didn't work

can you give me a hint what's going wrong?

**Comment by Vladinator** [comment]
Slow response, but I patched this behavior into the addon. It should be live with the next update. It would allow you to specify [color=paladin] and give you the pink color.
