### ISSUE TITLE
Taint

### ISSUE THREAD

**Issue by glassleo** [Vladinator/wow-addon-friendlistcolors#4]
This addon is causing taint in the Group Finder frame. Happens consistently when trying to list a M+ key for example.

4x [ADDON_ACTION_BLOCKED] AddOn 'FriendListColors' tried to call the protected function 'SetEntryTitle()'.

**Comment by Vladinator** [comment]
I looked into this and as part of the rewrite I had forgotten to rewrite another important bit that could cause any sort of taint, so this is part of the latest version release.

https://github.com/Vladinator/wow-addon-friendlistcolors/releases/tag/v9.2.7.220930
